coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 0%

ignore:
  - "cmd/"
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/testdata/"